# Generated by Django 4.2.27 on 2025-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_task_due_date_task_due_time_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_late',
            field=models.BooleanField(default=False),
        ),
    ]
